import { fileURLToPath } from 'node:url';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type pg from 'pg';

// apps/api/drizzle — the reviewed SQL files generated by `npm run db:generate`
const migrationsFolder = fileURLToPath(new URL('../../drizzle', import.meta.url));

/**
 * Applies every migration that hasn't run yet, in order, and records it in drizzle.__drizzle_migrations.
 * Takes a pool (not the app's db) so the test setup can migrate its own test database.
 */
export async function runMigrations(pool: pg.Pool): Promise<void> {
  await migrate(drizzle({ client: pool }), { migrationsFolder });
}
